---
title: "Lyrics progress"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Lyrics progress}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`heyahmama` does not have all the lyrics to all the songs yet.
This vignette shows the progress to this.

```{r}
library(heyahmama)
```

First we get all songs:

```{r}
songs <- get_songs()
message(paste0("There are ", nrow(songs), " songs"))
```

From those, we make a table of its filename
and if it has lyrics:

```{r}
t <- tibble::tibble(
  song_title = sort(songs$song_title)
)
t$filename = Vectorize(get_song_filename)(t$song_title)
t$has_lyrics <- NA

for (i in seq_len(nrow(t))) {
  song_title <- t$song_title[i]
  has_lyrics <- FALSE
  tryCatch(
    {
      get_song_lyrics(song_title)
      has_lyrics <- TRUE
    },
    error = function(msg) {}
  )
  t$has_lyrics[i] <- has_lyrics
    
}
knitr::kable(head(t))
```

And the missing songs only:

```{r}
knitr::kable(t[t$has_lyrics == FALSE,])
```

In a plot:

```{r}
tally <- dplyr::count(t, has_lyrics)
ggplot2::ggplot(
  tally,
  ggplot2::aes(x = has_lyrics, y = n)
) + ggplot2::geom_col()
```
